### ISSUE TITLE
featured playlists tags and sorting

### ISSUE THREAD

**Issue by IanWalston** [IanWalston/qasong#117]
- [x] add tags to each featured playlist
- [ ] add dropdown to top of featured playlist component that sorts featured playlists by tag

**Comment by Jasper-Mui** [comment]
I would like to try this.

**Comment by unjown** [comment]
> I would like to try this.

@Jasper-Mui just PR it :smile:

**Comment by Jardimjose** [comment]
Please, go ahead. Happy coding ☺️

**Comment by IanWalston** [comment]
thanks @Jasper-Mui
