### ISSUE TITLE
Horizontal Scroll

### ISSUE THREAD

**Issue by saitejan2011** [IanWalston/qasong#126]
Qasong Application is a centered screen and there will be absolutely no content in the rest of its area. An issue spotted as **Horizontal Scroll** in the bottom of the page. Need to fix that..!

**Comment by IanWalston** [comment]
@saitejan2011 I think I see what you mean. Are you having this issue on mobile browser? I see it happening on Safari on my iphone.

**Comment by IanWalston** [comment]
fixed. thanks again @saitejan2011
