### ISSUE TITLE
change loading animation image

### ISSUE THREAD

**Issue by IanWalston** [IanWalston/qasong#130]
currently, our loading animation is a spinning image of a vinyl with the qasong logo on it. 

Our designer made a better image for this that we should be using:

![loading](https://user-images.githubusercontent.com/42522279/99147826-f20bd400-2651-11eb-9ec3-8c1f057bbf91.png)

**Comment by unjown** [comment]
@IanWalston make sure we have a 2021 version :) cuz its near

**Comment by zjjiang2** [comment]
Hi, I would like to attempt closing this issue along with Issue #142 .

**Comment by IanWalston** [comment]
thanks @zjjiang2
