### ISSUE TITLE
Clicking Remove Song From Queue Plays the Song

### ISSUE THREAD

**Issue by Wei-J-Huang** [IanWalston/qasong#145]
I noticed that in the queue list view, if I click on remove song from the queue, this would removed the song but however also triggers the song to play, this would create a unpleasant user experience since they would need to manually stop the song.

**Comment by Wei-J-Huang** [comment]
I am working on a fix for this myself.

**Comment by IanWalston** [comment]
Thanks! One possible fix would probably involve e.stopPropagation() or something
