### ISSUE TITLE
Billboard Button in the Desktop Menu is disabled when there are no items in the queue

### ISSUE THREAD

**Issue by zjjiang2** [IanWalston/qasong#148]
I'm not sure if this is intentional or not, but as the title suggests:
![image](https://user-images.githubusercontent.com/71283454/99637762-4d074780-2a13-11eb-8de0-3968352a59a5.png)

A possible fix can be removing one line from ```frontend\src\components\AppBar\DesktopMenu\DesktopMenu.js```
![image](https://user-images.githubusercontent.com/71283454/99638054-b38c6580-2a13-11eb-962e-2472ecdbc9cf.png)
![image](https://user-images.githubusercontent.com/71283454/99638181-db7bc900-2a13-11eb-927d-d2ff1e1df394.png)

**Comment by unjown** [comment]
what do you mean? whats wrong?

also from what i know we removed that i was changed

**Comment by IanWalston** [comment]
thanks @zjjiang2 , this was temporary during development and is fixed now
