### ISSUE TITLE
better empty state for "queue" page

### ISSUE THREAD

**Issue by IanWalston** [IanWalston/qasong#157]
currently, if you visit the queue page while your queue is empty, you get the text "no queue"

lets make a better empty state, that could include:
     - a placeholder object that resembles what the queue would look like if it had song in it
     - instructions on how to search for songs and add them to your queue 
     - whatever else you think is good

**Comment by sanji11** [comment]
Hi, I would like to give it a try. Please assign it to me :)

**Comment by IanWalston** [comment]
@sanji11 sure go for it!

**Comment by IanWalston** [comment]
that fixed it, good job
