### ISSUE TITLE
Billboard top image not found error

### ISSUE THREAD

**Issue by unjown** [IanWalston/qasong#161]
![image](https://user-images.githubusercontent.com/71381907/99877521-c5e7e880-2c39-11eb-8550-b1a7deaaf0ae.png)

**Comment by IanWalston** [comment]
sometimes the billboardtop100 api sends up broken image urls in the response. lets put in a fallback image to display when theirs doesn't load

**Comment by unjown** [comment]
> sometimes the billboardtop100 api sends up broken image urls in the response. lets put in a fallback image to display when theirs doesn't load

k
