### ISSUE TITLE
Loader image

### ISSUE THREAD

**Issue by unjown** [IanWalston/qasong#198]
Make the image smaller and use css to resize so the loading speed will be faster

**Comment by IanWalston** [comment]
not sure about this one. I'd love to hear from some designers about it. I know Nova intended it to be a larger image

**Comment by unjown** [comment]
if we dont change
pros: nicer image
cons: load speed slower

**Comment by IanWalston** [comment]
it's actually asynchronous so rendering the loading image doesn't effect the time it takes the server to respond with the results
