### ISSUE TITLE
Browser default scrollbar 

### ISSUE THREAD

**Issue by Jardimjose** [IanWalston/qasong#212]
At the moment the scrollbar breaks the overall appearance of the web app, let's overwrite the styling for Chrome, Firefox, Edge,  while still maintaining the scroll functionality

**Comment by unjown** [comment]
https://github.com/theKashey/react-remove-scroll

**Comment by unjown** [comment]
up

**Comment by unjown** [comment]
link was given

**Comment by Jardimjose** [comment]
- @unjown the package only removes the scroll bar and doesnt retain functionality. I've tried it already

**Comment by IanWalston** [comment]
eh
