### ISSUE TITLE
buttons on queue cards to move the card up or down the queue

### ISSUE THREAD

**Issue by IanWalston** [IanWalston/qasong#64]
currently, you can re order a queue only by the "drag and drop" feature, which is at the moment a bit inconsistant

lets give the users tiny arrow buttons they can use when the drag and drop fails

**Comment by zjjiang2** [comment]
Hello, I would like to work on this issue. Please allow me to give it a try.

**Comment by Jardimjose** [comment]
Awesome! You're more than welcome to give it a try.

**Comment by zjjiang2** [comment]
![image](https://user-images.githubusercontent.com/71283454/97778481-dc74b580-1b4d-11eb-91f4-26ccc902c0d3.png)
There isn't much space inside the box, would this be an ideal size for the buttons?
Please let me know if you have one in mind.

**Comment by Jardimjose** [comment]
You're welcome to try and resize the box to make it look better. I think you can change the size of the materialUI buttons using fontSize
